### ISSUE TITLE
oppp2021: docs/lang TO-DO

### ISSUE THREAD

**Issue by CamberLoid** [OI-wiki/i18n#129]
- [ ] ./class.md
- [ ] ./const.md
- [ ] ./file-op.md
- [ ] ./func.md
- [ ] ./java.md
- [ ] ./loop.md
- [ ] ./namespace.md
- [ ] ./new.md
- [ ] ./op.md
- [ ] ./op-overload.md(new)
- [ ] ./pas-cpp.md
- [ ] ./pointer.md
- [ ] ./python.md
- [ ] ./reference.md
- [ ] ./struct.md
- [ ] ./value-category.md
- [ ]  ./var.md
