### ISSUE TITLE
ospp2021: TODO of docs/tools

### ISSUE THREAD

**Issue by CamberLoid** [OI-wiki/i18n#130]
- [ ] cmd.md
- [x] index.md
- [ ] judgers.md
- [ ] latex.md
- [ ] oj-tool.md
- [ ] polygon.md
- [ ] special-judge.md
- [ ] wsl.md 

Editors:
- [x] editor/atom.md
- [x] editor/devcpp.md
- [ ] editor/eclipse.md
- [x] editor/emacs.md
- [ ] editor/geany.md
- [ ] editor/guide.md (Possible #wontfix)
- [ ] editor/kate.md
- [ ] editor/npp.md
- [ ] editor/sublime3.md
- [ ] editor/vim.md (工作量过大)
- [ ] editor/vscode.md
- [ ] editor/xcode.md (图片部分 #Wontfix)

testlib:
- [ ] checker.md
- [ ] general.md
- [ ] generator.md
- [ ] index.md
- [ ] interactor.md
- [ ] validator.md
